<a href="https://colab.research.google.com/github/Jake0925/DeepLearning/blob/master/6_1_SoftMax.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://github.com/hunkim/DeepLearningZeroToAll/blob/master/tf2/tf2-06-1-softmax_classifier.py

데이터

In [ ]:
import tensorflow as tf
import numpy as np

# x1, x2, x3, x4
x_raw = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_raw = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

x_data = np.array(x_raw, dtype=np.float32)
y_data = np.array(y_raw, dtype=np.float32)


모델학습

In [1]:
nb_classes = 3 # class 종류갯수

tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.Dense(input_dim=4, units=nb_classes, use_bias=True))  # input_dim=4 4개의 요소(x1,x2,x3,x4), use_bias is True, by default

# use softmax activations: softmax = exp(logits) / reduce_sum(exp(logits), dim)
tf.model.add(tf.keras.layers.Activation('softmax'))

# 비용함수 categorical_crossentropy를 사
tf.model.compile(loss='categorical_crossentropy', optimizer=tf.keras.optimizers.SGD(lr=0.1), metrics=['accuracy'])
tf.model.summary()

history = tf.model.fit(x_data, y_data, epochs=2000)


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 3)                 15        
                                                                 
 activation (Activation)     (None, 3)                 0         
                                                                 
Total params: 15 (60.00 Byte)
Trainable params: 15 (60.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
Epoch 1/2000
1/1 [==============================] - 2s 2s/step - loss: 4.9729 - accuracy: 0.2500
Epoch 2/2000
1/1 [==============================] - 0s 64ms/step - loss: 4.6701 - accuracy: 0.2500
Epoch 3/2000
1/1 [==============================] - 0s 40ms/step - loss: 4.3836 - accuracy: 0.2500
Epoch 4/2000
1/1 [==============================] - 0s 49ms/step - loss: 4.1145 - accuracy: 0.1250
Epoch 5/2000
1/1 [======

결과 예측

In [3]:
# Testing & One-hot encoding
a = tf.model.predict(np.array([[1, 11, 7, 9]]))
print(a, tf.keras.backend.eval(tf.argmax(a, axis=1))) # 결론은 두번째 요소가 가장 높은 확률값을 갖는다 [0 1 0]

1/1 [==============================] - 0s 29ms/step
[[0.15900578 0.838302   0.00269217]] [1]


In [4]:
b = tf.model.predict(np.array([[1, 3, 4, 3]]))
print(b, tf.keras.backend.eval(tf.argmax(b, axis=1))) # 첫번째 요소가 가장 높은 확률을 갖는다 [1 0 0]

1/1 [==============================] - 0s 24ms/step
[[0.6652234  0.23572671 0.09904986]] [0]


In [7]:
# or use argmax embedded method, predict_classes
c = tf.model.predict(np.array([[1, 1, 0, 1]]))
c_onehot = np.argmax(c, axis=-1) # argmax를 통해 몇번째 요소가 가장큰 값을 갖는지 인덱스 번호를 알려준다
print('확률: ', c)
print('one hot: ', c_onehot)

1/1 [==============================] - 0s 21ms/step
확률:  [[0.00244481 0.07678713 0.9207681 ]]
one hot:  [2]


In [8]:
all = tf.model.predict(np.array([[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]])) # 여러개를 질문
all_onehot = np.argmax(all, axis=-1) # 최대값을 갖는 인덱스번호
print(all)
print(all_onehot)

1/1 [==============================] - 0s 20ms/step
[[0.15900587 0.8383019  0.00269217]
 [0.6652234  0.23572676 0.09904987]
 [0.00244481 0.07678713 0.9207681 ]]
[1 0 2]
