<a href="https://colab.research.google.com/github/Jake0925/DeepLearning/blob/master/Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Random

In [1]:
import numpy as np

In [2]:
np.random.rand(3,3)  # 0~1 사이의 난수생성

np.random.randint(0, 10, size = 10)  # randint(최소값, 최대값, 배열사이즈) 최소값이상 최대값 미만의 값을 출력
np.random.randint(10, size = 10)  # 위의 함수와 같은의미이다


np.random.randint(0, 10, (3,3)) # 3 X 3 행렬의 0~10안의 랜덤값을 값는 배열 출력

array([[1, 9, 6],
       [4, 7, 6],
       [4, 3, 9]])

cumsum
- 각 원소들의 누적 합을 표시

In [13]:
a =  np.arange(0,8).reshape(2,4)

b = np.cumsum(a)
c = np.cumsum(a, dtype = float) # 값의 변수 type을 설정하면서 누적
d = np.cumsum(a, axis = 0)      # axis = 0은 같은 column 끼리의 누적 합을 함
e = np.cumsum(a, axis = 1)      # 같은 row끼리의 누적 합을 함

print('a: \n', a)
print('b: ', b)
print('c: ', c) 
print('d: \n', d) 
print('e: \n', e) 

a: 
 [[0 1 2 3]
 [4 5 6 7]]
b:  [ 0  1  3  6 10 15 21 28]
c:  [ 0.  1.  3.  6. 10. 15. 21. 28.]
d: 
 [[ 0  1  2  3]
 [ 4  6  8 10]]
e: 
 [[ 0  1  3  6]
 [ 4  9 15 22]]
